/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.ImageIcon;

/**
 *
 * @author tunac
 */
public class PetShop extends javax.swing.JFrame
{

    /**
     * Creates new form PetShop
     */
    ImageIcon Tasma = new ImageIcon("PhotosForAnimals/KöpekTasma.jpg");
    ImageIcon KöpekMama = new ImageIcon("PhotosForAnimals/KöpekMama.jpg");
    ImageIcon KöpekOyuncak = new ImageIcon("PhotosForAnimals/KöpekKemik.jpg");
    ImageIcon Kafes = new ImageIcon("PhotosForAnimals/Kafes.jpg");
    ImageIcon KediMama = new ImageIcon("PhotosForAnimals/KediMama.jpg");
    ImageIcon KediOyuncak = new ImageIcon("PhotosForAnimals/KediTırmalama.jpg");

    int count = 0;

    StartFrame sf;

    public PetShop(StartFrame s)
    {
        initComponents();
        TasmaLbl.setIcon(Tasma);
        KöpekMamaLbl.setIcon(KöpekMama);
        KöpekOyuncakLbl.setIcon(KöpekOyuncak);
        KafesLbl.setIcon(Kafes);
        KediMamaLbl.setIcon(KediMama);
        KediOyuncakLbl.setIcon(KediOyuncak);
        sf = s;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TasmaLbl = new javax.swing.JLabel();
        KöpekMamaLbl = new javax.swing.JLabel();
        KöpekOyuncakLbl = new javax.swing.JLabel();
        KafesLbl = new javax.swing.JLabel();
        KediMamaLbl = new javax.swing.JLabel();
        KediOyuncakLbl = new javax.swing.JLabel();
        ToplamHesap = new javax.swing.JTextField();
        HesapBtn = new javax.swing.JButton();
        Tasmacbx = new javax.swing.JCheckBox();
        KöpekMamaCbx = new javax.swing.JCheckBox();
        KöpekOyuncakCbx = new javax.swing.JCheckBox();
        KafesCbx = new javax.swing.JCheckBox();
        KediMamaCbx = new javax.swing.JCheckBox();
        KediOyuncakCbx = new javax.swing.JCheckBox();
        TasmaPrice = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        KartlaÖdemeBtn = new javax.swing.JButton();
        NakitÖdeBtn = new javax.swing.JButton();
        İndirimKodu = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        İndirimBtn = new javax.swing.JButton();
        close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ToplamHesap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToplamHesapActionPerformed(evt);
            }
        });

        HesapBtn.setText("Complete your shopping");
        HesapBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HesapBtnActionPerformed(evt);
            }
        });

        Tasmacbx.setText("Add");
        Tasmacbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TasmacbxActionPerformed(evt);
            }
        });

        KöpekMamaCbx.setText("Add");
        KöpekMamaCbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KöpekMamaCbxActionPerformed(evt);
            }
        });

        KöpekOyuncakCbx.setText("Add");
        KöpekOyuncakCbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KöpekOyuncakCbxActionPerformed(evt);
            }
        });

        KafesCbx.setText("Add");
        KafesCbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KafesCbxActionPerformed(evt);
            }
        });

        KediMamaCbx.setText("Add");
        KediMamaCbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KediMamaCbxActionPerformed(evt);
            }
        });

        KediOyuncakCbx.setText("Add");
        KediOyuncakCbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KediOyuncakCbxActionPerformed(evt);
            }
        });

        TasmaPrice.setText("100TL");

        jLabel1.setText("150TL");

        jLabel2.setText("50TL");

        jLabel3.setText("200TL");

        jLabel4.setText("140TL");

        jLabel5.setText("350TL");

        KartlaÖdemeBtn.setText("Credit Card Payment");
        KartlaÖdemeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KartlaÖdemeBtnActionPerformed(evt);
            }
        });

        NakitÖdeBtn.setText("Cash Payment");
        NakitÖdeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NakitÖdeBtnActionPerformed(evt);
            }
        });

        jLabel6.setText("If You Have a Discount Code Enter:");

        İndirimBtn.setText("Apply");
        İndirimBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                İndirimBtnActionPerformed(evt);
            }
        });

        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(KafesLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(TasmaLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(KöpekMamaLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(KediMamaLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(131, 131, 131)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(KediOyuncakLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(KöpekOyuncakLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(154, 154, 154)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addComponent(KafesCbx)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(218, 218, 218)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(210, 210, 210)
                                .addComponent(KediMamaCbx)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(KediOyuncakCbx)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(8, 8, 8)))
                        .addGap(47, 47, 47)))
                .addGap(90, 90, 90))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(Tasmacbx))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(TasmaPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(KöpekMamaCbx)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(146, 146, 146))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(KöpekOyuncakCbx)
                        .addGap(138, 138, 138))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(KartlaÖdemeBtn)
                        .addGap(110, 110, 110)
                        .addComponent(NakitÖdeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(İndirimKodu, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(İndirimBtn)
                        .addGap(254, 254, 254))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(HesapBtn)
                        .addGap(343, 343, 343))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ToplamHesap, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(265, 265, 265))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TasmaLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KöpekMamaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KöpekOyuncakLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TasmaPrice)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KöpekMamaCbx)
                    .addComponent(Tasmacbx)
                    .addComponent(KöpekOyuncakCbx))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(KediMamaLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KafesLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KediOyuncakLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KafesCbx)
                    .addComponent(KediMamaCbx)
                    .addComponent(KediOyuncakCbx))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(HesapBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ToplamHesap, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(İndirimKodu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(İndirimBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NakitÖdeBtn)
                    .addComponent(KartlaÖdemeBtn)
                    .addComponent(close))
                .addGap(22, 22, 22))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void KediMamaCbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KediMamaCbxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_KediMamaCbxActionPerformed

    private void TasmacbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TasmacbxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_TasmacbxActionPerformed

    private void KöpekMamaCbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KöpekMamaCbxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_KöpekMamaCbxActionPerformed

    private void KöpekOyuncakCbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KöpekOyuncakCbxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_KöpekOyuncakCbxActionPerformed

    private void KafesCbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KafesCbxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_KafesCbxActionPerformed

    private void KediOyuncakCbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KediOyuncakCbxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_KediOyuncakCbxActionPerformed

    private void HesapBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HesapBtnActionPerformed
        // TODO add your handling code here:
        count = 0;

        if (KediMamaCbx.isSelected())
        {
            count += 140;
        }
        if (Tasmacbx.isSelected())
        {
            count += 100;
        }
        if (KöpekMamaCbx.isSelected())
        {
            count += 150;
        }
        if (KöpekOyuncakCbx.isSelected())
        {
            count += 50;
        }
        if (KafesCbx.isSelected())
        {
            count += 200;
        }
        if (KediOyuncakCbx.isSelected())
        {
            count += 350;
        }

        if (!KediMamaCbx.isSelected() && !Tasmacbx.isSelected() && !KöpekMamaCbx.isSelected() && !KöpekOyuncakCbx.isSelected()
                && !KafesCbx.isSelected() && !KediOyuncakCbx.isSelected())
        {
            ToplamHesap.setText("Please select product!");
        } else
        {
            //ToplamHesap.setText("ALIŞVERİŞ TAMAMLANDI"); yeni satır gibi yazmadım
            ToplamHesap.setText("Total payment: " + count + "TL");
        }


    }//GEN-LAST:event_HesapBtnActionPerformed

    private void ToplamHesapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToplamHesapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ToplamHesapActionPerformed

    private void KartlaÖdemeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KartlaÖdemeBtnActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_KartlaÖdemeBtnActionPerformed

    private void NakitÖdeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NakitÖdeBtnActionPerformed
        // TODO add your handling code here:
        int fiyat = count;
        if (count == fiyat)
        {
            fiyat = count - (count / 10);

            ToplamHesap.setText("10% discount applied. New payment: " + fiyat);
        }
    }//GEN-LAST:event_NakitÖdeBtnActionPerformed

    private void İndirimBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_İndirimBtnActionPerformed
        // TODO add your handling code here:
        if (İndirimKodu.getText().equalsIgnoreCase("Hayvanlarıkoruyun"))
        {
            ToplamHesap.setText("Discount Code Successful! New payment: " + (count - (count / 10)));
            count = count - (count / 10);

            İndirimBtn.setEnabled(false);
        }
    }//GEN-LAST:event_İndirimBtnActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_closeActionPerformed
    {//GEN-HEADEREND:event_closeActionPerformed
        this.setVisible(false);
        sf.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_closeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HesapBtn;
    private javax.swing.JCheckBox KafesCbx;
    private javax.swing.JLabel KafesLbl;
    private javax.swing.JButton KartlaÖdemeBtn;
    private javax.swing.JCheckBox KediMamaCbx;
    private javax.swing.JLabel KediMamaLbl;
    private javax.swing.JCheckBox KediOyuncakCbx;
    private javax.swing.JLabel KediOyuncakLbl;
    private javax.swing.JCheckBox KöpekMamaCbx;
    private javax.swing.JLabel KöpekMamaLbl;
    private javax.swing.JCheckBox KöpekOyuncakCbx;
    private javax.swing.JLabel KöpekOyuncakLbl;
    private javax.swing.JButton NakitÖdeBtn;
    private javax.swing.JLabel TasmaLbl;
    private javax.swing.JLabel TasmaPrice;
    private javax.swing.JCheckBox Tasmacbx;
    private javax.swing.JTextField ToplamHesap;
    private javax.swing.JButton close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton İndirimBtn;
    private javax.swing.JTextField İndirimKodu;
    // End of variables declaration//GEN-END:variables
}
